

POST http://localhost:5050/api/tasks/add
Content-Type: application/json

{
  "title": "Test Testsson",
  "description": "test@mail.com",
  "points": 1
}

###

DELETE http://localhost:5050/api/tasks/delete/Ersätt detta med ID du vill ta bort